[package]
name = "osmosis"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.17", features = ["json"] }
serde = { version = "1.0.163", features = ["derive"] }
serde-aux = "4.2.0"
tokio = { version = "1.28.1", features = ["full"] }
tokio-postgres = "0.7.8"
